local <const> AESDefs = {
  -- graf_mouse
  grmo_arrow = 0,
  grmo_text_crsr = 1,
  grmo_hourglass = 2,
  grmo_point_hand = 3,
  grmo_flat_hand = 4,
  grmo_thin_cross = 5,
  grmo_thick_cross = 6,
  grmo_outln_cross = 7,
  grmo_user_def = 255,
  grmo_m_off = 256,
  grmo_m_on = 257,
  -- graf_mkstate
  grmk_left_button = 1,
  grmk_right_button = 2,
  grmk_right_shift = 1,
  grmk_left_shift = 2,
  grmk_control = 4,
  grmk_alt = 8,
  -- evnt_button
  evbu_left_button = 1,
  evbu_right_button = 2,
  evbu_right_shift = 1,
  evbu_left_shift = 2,
  evbu_control = 4,
  evbu_alt = 8,
  -- evnt_dclick
  evdc_read = 0,
  evdc_set = 1,
  -- evnt_mouse
  evmo_enter = 0,
  evmo_leave = 1,
  -- evnt_multi
  evmu_keybd = 1,
  evmu_button = 2,
  evmu_m1 = 4,
  evmu_m2 = 8,
  evmu_mesag = 16,
  evmu_timer = 32,
  -- wind_create
  wicr_name = 1,
  wicr_closer = 2,
  wicr_fuller = 4,
  wicr_mover = 8,
  wicr_info = 16,
  wicr_sizer = 32,
  wicr_uparrow = 64,
  wicr_dnarrow = 128,
  wicr_vslide = 256,
  wicr_lfarrow = 512,
  wicr_rtarrow = 1024,
  wicr_hslide = 2048,
  -- wind_get
  wige_workxywh = 4,
  wige_currxywh = 5,
  wige_prevxywh = 6,
  wige_fullxywh = 7,
  wige_hslide = 8,
  wige_vslide = 9,
  wige_top = 10,
  wige_firstxywh = 11,
  wige_nextxywh = 12,
  wige_hslsize = 15,
  wige_vslsize = 16,
  wige_screen = 17,
  -- wind_set
  wise_kind = 1,
  wise_name = 2,
  wise_info = 3,
  wise_currxywh = 5,
  wise_hslide = 8,
  wise_vslide = 9,
  wise_top = 10,
  wise_newdesk = 14,
  wise_hslsize = 15,
  wise_vslsize = 16,
  -- wind_update
  wiup_end_update = 0,
  wiup_beg_update = 1,
  wiup_end_mctl = 2,
  wiup_beg_mctl = 3,
  -- wind_calc
  wica_border = 0,
  wica_work = 1,
  -- form_dial
  fodi_start = 0,
  fodi_grow = 1,
  fodi_shrink = 2,
  fodi_finish = 3,
  -- rsrc_gaddr
  rsga_tree = 0,
  rsga_object = 1,
  rsga_tedinfo = 2,
  rsga_iconblk = 3,
  rsga_bitblk = 4,
  rsga_string = 5,
  rsga_imagedata = 6,
  rsga_obspec = 7,
  rsga_teptext = 8,
  rsga_teptmplt = 9,
  rsga_tepvalid = 10,
  rsga_ibpmask = 11,
  rsga_ibpdata = 12,
  rsga_ibptext = 13,
  rsga_bipdata = 14,
  rsga_frstr = 15,
  rsga_frimg = 16,
  -- objc_draw
  obdr_root = 0,
  obdr_max_depth = 8,
  -- objc_edit
  obed_start = 0,
  obed_init = 1,
  obed_char = 2,
  obed_ends = 3,
  -- objc_change
  obch_no_redraw = 0,
  obch_redraw = 1,
  obch_normal = 0,
  obch_selected = 1,
  obch_crossed = 2,
  obch_checked = 4,
  obch_disabled = 8,
  obch_outlined = 16,
  obch_shadowed = 32,
  -- objc_type
  obty_box = 20,
  obty_text = 21,
  obty_boxtext = 22,
  obty_image = 23,
  obty_userdef = 24,
  obty_ibox = 25,
  obty_button = 26,
  obty_boxchar = 27,
  obty_string = 28,
  obty_ftext = 29,
  obty_fboxtext = 30,
  obty_icon = 31,
  obty_title = 32,
  obty_cicon = 33,
  -- objc_flags
  obfl_selectable = 1,
  obfl_default = 2,
  obfl_exit = 4,
  obfl_editable = 8,
  obfl_rbutton = 16,
  obfl_lastob = 32,
  obfl_touchexit = 64,
  obfl_hidetree = 128,
  obfl_indirect = 256,
  -- menu_bar
  meba_erase = 0,
  meba_show = 1,
  -- menu_icheck
  meic_uncheck = 0,
  meic_check = 1,
  -- menu_ienable
  meie_disable = 0,
  meie_enable = 1,
  -- menu_tnormal
  metn_reverse = 0,
  metn_normal = 1,
  -- evnt_mesag
  evme_mn_selected = 10,
  evme_wm_redraw = 20,
  evme_wm_topped = 21,
  evme_wm_closed = 22,
  evme_wm_fulled = 23,
  evme_wm_arrowed = 24,
  evme_wm_hslid = 25,
  evme_wm_vslid = 26,
  evme_wm_sized = 27,
  evme_wm_moved = 28,
  evme_wm_newtop = 29,
  evme_wm_untopped = 30,
  evme_ac_open = 40,
  evme_ac_close = 41,
  -- evme_wm_arrowed actions
  wmar_pageup = 0,
  wmar_pagedown = 1,
  wmar_lineup = 2,
  wmar_linedown = 3,
  wmar_pageleft = 4,
  wmar_pageright = 5,
  wmar_columnleft = 6,
  wmar_columnright = 7,
  -- shel_write
  shwr_tosapp = 0,
  shwr_gemapp = 1
}

return AESDefs
